hpa:
  enable: true
  minReplicas: 3
  maxReplicas: 7
  cpu:
    averageUtilization: 50
  memory:
    averageUtilization: 75

deployment:
  enable: true
  image: nginx
  imagePullPolicy: IfNotPresent
  replicas: 3
  restartPolicy: Always
  resources:
    requests:
      cpu: "200m"
      memory: "200Mi"
    limits:
      cpu: "400m"
      memory: "400Mi"
  args:
  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3