hpatest:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "400m"
    memory: "400Mi"
  minReplicas: 3
  maxReplicas: 7

deployment:
  name: read-live-test
  namespace: default
  image: nginx
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  containerLabels:
    app: read-live-test-nginx
  resources:
    requests:
      cpu: "200m"
      memory: "200Mi"
    limits:
      cpu: "400m"
      memory: "400Mi"
  args:
  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3