apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name | quote }}
  namespace: {{ .Values.deployment.namespace | quote }}
spec:
  selector:
    matchLabels:
      {{ .Values.deployment.containerLabels | toYaml | indent 8 }}
  template:
    metadata:
      labels:
        {{ .Values.deployment.containerLabels | toYaml | indent 8 }}
    spec:
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      containers:
        - name: {{ .Values.deployment.name | quote }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy | quote }}
          args:
            {{- range .Values.deployment.args }}
              - {{ . | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.hpatest.requests.cpu | quote }}
              memory: {{ .Values.hpatest.requests.memory | quote }}
            limits:
              cpu: {{ .Values.hpatest.limits.cpu | quote }}
              memory: {{ .Values.hpatest.limits.memory | quote }}
          readinessProbe:
          livenessProbe:
